#!/bin/sh
#
# Scott Krulcik
#
# Partially derived from CMU's bashrc_gpi and the linux example found in
# /usr/share/doc/bash/examples/startup-files
#
# To use on Mac, put `source ~/.bashrc` in the .bash_profile file
#

# If not running interactively, don't do anything
case $- in
    *i*) ;;
      *) return;;
esac

# check the window size after each command and, if necessary,
# update the values of LINES and COLUMNS.
shopt -s checkwinsize

# === Appearance ===
alias grep='grep --color=auto'
shopt -s checkwinsize         # Update window size after each command

# History configuration
export HISTCONTROL=ignoreboth # Don't store duplicates
export HISTSIZE=10000
export HISTFILESIZE=10000
shopt -s histappend           # Append only to history

# Remove case sensitive completion
if [ -f /etc/bash_completion ]; then
     . /etc/bash_completion
fi
bind "set completion-ignore-case on"

## Useful aliases
alias ccomp='gcc -Wall -Wextra -Werror -std=c99 -pedantic'
alias valgrind-leak='valgrind --leak-check=full --show-reachable=yes'
alias hidden='ls -a | grep "^\..*"'
alias linelength='wc -L'

# Git Aliases
alias ga='git add'
alias gb='git branch'
alias gc='git commit'
alias gd='git diff'
alias gdc='git diff --cached'
alias gl='git log --graph --decorate --color --pretty=oneline -n 20 --abbrev-commit'
alias gla='git log --graph --decorate --color --pretty=format:"%C(yellow)%H%C(green)%d%C(reset)%n%x20%cd%n%x20%cn%x20(%ce)%n%x20%s%n" --stat'
alias gm='git merge'
alias gpr='git pull --rebase'
alias gs='git status -s'
alias gsa='git status'
alias gundo='git checkout --'
alias greset='git reset HEAD'
# `gdi $number` shows the diff between the state `$number` revisions ago and the current state
alias gdi='d() { git diff --patch-with-stat HEAD~$1; }; git diff-index --quiet HEAD -- || clear; d'
alias grbc='git rebase --continue'
grbi() { git rebase -i HEAD~$1; }
clone() {
    git clone "git@github.com:$1/$2.git";
    go-navigate $2 || cd "$2";
}

# Makes a directory, then moves into it
mkcd() { mkdir -p "$@" && go-navigate "$_"; }

# Export resource path to a global variable
export RESOURCE_PATH=`cat ~/.krulcik_resource_path`
# Add resource bin to path
export PATH="$RESOURCE_PATH/bin:$PATH"
if [ -d $HOME/.cargo ];
then
  # Rust bin
  export PATH="$HOME/.cargo/bin:$PATH"
fi

# Create a consistently-available ~/tmp directory that holds only the current
# user's temporary files
if [ -z $USER_TMP_DIR ];
then
    export USER_TMP_DIR="/tmp/$USER";
fi
mkdir -p "$USER_TMP_DIR";
if [ ! -e "$HOME/tmp" ];
then
    ln -s "$USER_TMP_DIR" "$HOME/tmp";
fi

# Suggested by jez
vman() {
    vim -c "SuperMan $*"

    if [ "$?" != "0" ]; then
        echo "No manual entry for $*"
    fi
}

## Mac-specific changes
if [[ "$(uname)" = "Darwin" ]]
then
  # Colored ls
  alias ls='ls -G'

  # Homebrew settings
  export PATH=/usr/local/bin:$PATH
  alias vim='/usr/local/bin/vim'
  export EDITOR='/usr/local/bin/vim'

  # Start up ssh-agent
  [[ -z $SSH_AGENT_PID && -z $DISPLAY ]] &&
    exec -l ssh-agent $SHELL -c "bash --login"
else
  alias ls='ls --color=auto'
  # Linux shutdown command (works on RasPi, haven't tested on others)
  alias shutdown="sudo shutdown -h now"
  alias pbcopy='xclip -selection clipboard'
  alias pbpaste='xclip -selection clipboard -o'
fi

# Use the "go-navigate" function instead of cd https://github.com/skrulcik/go-navigator
. $RESOURCE_PATH/bin/go-navigator/go-navigate
alias gn='go-navigate'

## Hostname-specific changes
promptText=""
export TERM=xterm-256color
export EDITOR='vim'
case $(text2lower $(hostname)) in
    "skrulcik mbp")
        # Disable kqueue in tmux 2.2 (broken on OSX, runs fine despite this)
        export EVENT_NOKQUEUE=1
        # Update classpath
        export CLASSPATH="/Users/Scott/Projects/Java/jars":$CLASSPATH
        # Promp is blank, this is my main computer
        export promptText=""
        # ocaml
        eval $(opam config env)
        alias ocaml='rlwrap ocaml'
        # Rust configuration
        export PATH=/Users/Scott/.cargo/bin:$PATH
        # Go configuration
        export GOPATH=$HOME/go
        export PATH=$PATH:$GOPATH/bin
        # Random executables I make
        export PATH="$HOME/bin:$PATH"
        export TERM=xterm-256color-italic
        ;;
    "scottylabs")
        export promptText="sl"
        ;;
    unix*.andrew.cmu.edu)
        export promptText="andrew"
        ;;
    *)
        export promptText="\h"
        ;;
esac
export PS1="\[\e[37m\]$promptText\[\e[m\]\[\033[01;34m\]>\[\033[00m\] ";

# Import named bash modules that aren't applicable to all computers
# Modules should be imported last, to ensure PATH is set to its final value
_import_module() {
    if [ "$(which "$1")" ];
    then
        source "$RESOURCE_PATH/dotfiles/bash_modules/$1.bash";
    fi
}
_import_module 'tmux';
_import_module 'vim';
_import_module 'fzf';

